# Generated by Django 5.1 on 2024-09-14 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=255)),
                ('details', models.TextField()),
            ],
            options={
                'db_table': 'dictionary',
            },
        ),
        migrations.CreateModel(
            name='DividendVolatility',
            fields=[
                ('stock_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('prev_dividend_rate', models.FloatField()),
                ('pred_dividend_rate', models.FloatField()),
                ('dividend_stability', models.CharField(max_length=1)),
                ('volatility', models.CharField(max_length=1)),
                ('year', models.IntegerField()),
                ('stock_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dividend_volatility',
            },
        ),
        migrations.CreateModel(
            name='Mbti',
            fields=[
                ('stock_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('mbti', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'mbti',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('stock_code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('pubDate', models.DateTimeField(max_length=30)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('originallink', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TestOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('points', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.testoption'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result1', models.CharField(max_length=100)),
                ('result2', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'test_result',
            },
        ),
        migrations.CreateModel(
            name='UserStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(blank=True, max_length=10, null=True)),
                ('mbti', models.CharField(blank=True, max_length=10, null=True)),
                ('stock_id', models.ForeignKey(db_column='stock_id', on_delete=django.db.models.deletion.CASCADE, to='stocks.realtime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_list',
                'unique_together': {('user', 'stock_code')},
            },
        ),
    ]
