# Generated by Django 5.1 on 2024-09-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=255)),
                ('details', models.TextField()),
            ],
            options={
                'db_table': 'datawarehouse',
            },
        ),
    ]
