# Generated by Django 5.1 on 2024-09-06 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userstock',
            table='favorite_stock',
        ),
    ]
