# Generated by Django 5.1 on 2024-09-06 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userstock_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstock',
            name='stock_code',
            field=models.ForeignKey(db_column='stock_code', on_delete=django.db.models.deletion.CASCADE, to='main.realtimestock'),
        ),
        migrations.AlterModelTable(
            name='userstock',
            table='favorite_list',
        ),
    ]
