# Generated by Django 5.1 on 2024-09-06 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userstock_stock_code_alter_userstock_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstock',
            name='stock_id',
            field=models.ForeignKey(db_column='stock_id', default=1234560, on_delete=django.db.models.deletion.CASCADE, to='main.realtimestock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userstock',
            name='stock_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
