# Generated by Django 5.1 on 2024-09-12 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_datawarehouse_table'),
        ('main', '0004_userstock_stock_id_alter_userstock_stock_code'),
    ]

    operations = [
    ]
