# Generated by Django 5.1 on 2024-09-12 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20240912_0119'),
        ('stocks', '0010_realtime_remove_market_unique_stockname_pricetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstock',
            name='stock_id',
            field=models.ForeignKey(db_column='stock_id', on_delete=django.db.models.deletion.CASCADE, to='stocks.realtime'),
        ),
        migrations.DeleteModel(
            name='RealTimeStock',
        ),
    ]
