# Generated by Django 5.1 on 2024-09-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('StockName', models.CharField(db_column='StockName', max_length=255, primary_key=True, serialize=False)),
                ('CurrentPoint', models.TextField(blank=True, db_column='CurrentPoint', null=True)),
                ('UpDownPoint', models.TextField(blank=True, db_column='UpDownPoint', null=True)),
                ('UpDownRate', models.TextField(blank=True, db_column='UpDownRate', null=True)),
                ('UpDownFlag', models.TextField(blank=True, db_column='UpDownFlag', null=True)),
                ('price_time', models.DateTimeField(db_column='price_time')),
            ],
            options={
                'db_table': 'market',
                'ordering': ['-price_time'],
                'unique_together': {('StockName', 'price_time')},
            },
        ),
        migrations.CreateModel(
            name='OnceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('closing_price', models.IntegerField()),
                ('hts_total', models.IntegerField()),
                ('prev_trading', models.IntegerField()),
                ('MA5', models.FloatField(blank=True, null=True)),
                ('MA20', models.FloatField(blank=True, null=True)),
                ('MA60', models.FloatField(blank=True, null=True)),
                ('MA120', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'once_time',
                'ordering': ['-date'],
                'unique_together': {('stock_code', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RealTime',
            fields=[
                ('stock_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=10)),
                ('status_code', models.CharField(max_length=20)),
                ('current_price', models.IntegerField()),
                ('UpDownPoint', models.IntegerField(blank=True, null=True)),
                ('PlusMinus', models.IntegerField(blank=True, null=True)),
                ('UpDownRate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('opening_price', models.IntegerField(blank=True, null=True)),
                ('high_price', models.IntegerField(blank=True, null=True)),
                ('low_price', models.IntegerField(blank=True, null=True)),
                ('price_time', models.DateTimeField(blank=True, null=True)),
                ('per', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pbr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stockcount', models.IntegerField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'real_time',
                'unique_together': {('stock_code', 'id')},
            },
        ),
    ]
