# Generated by Django 5.1 on 2024-09-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('closing_price', models.IntegerField()),
                ('hts_total', models.IntegerField()),
                ('prev_trading', models.IntegerField()),
                ('MA5', models.FloatField()),
                ('MA20', models.FloatField()),
                ('MA60', models.FloatField()),
                ('MA120', models.FloatField()),
            ],
            options={
                'db_table': 'once_time',
            },
        ),
    ]
