# Generated by Django 5.1 on 2024-09-23 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtime',
            options={'ordering': ['-price_time']},
        ),
    ]
