# Generated by Django 5.1 on 2024-09-03 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oncetime',
            options={'managed': False},
        ),
    ]
