# Generated by Django 5.1 on 2024-09-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_oncetime_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oncetime',
            options={'ordering': ['-date']},
        ),
    ]
