# Generated by Django 5.1 on 2024-09-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_oncetime_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncetime',
            name='MA120',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oncetime',
            name='MA20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oncetime',
            name='MA5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oncetime',
            name='MA60',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='oncetime',
            unique_together={('stock_code', 'date')},
        ),
    ]
