# Generated by Django 5.1 on 2024-09-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='current_point',
            field=models.TextField(blank=True, db_column='CurrentPoint', null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='price_time',
            field=models.DateTimeField(db_column='price_time'),
        ),
        migrations.AlterField(
            model_name='market',
            name='stock_name',
            field=models.TextField(db_column='StockName'),
        ),
        migrations.AlterField(
            model_name='market',
            name='up_down_flag',
            field=models.TextField(blank=True, db_column='UpDownFlag', null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='up_down_point',
            field=models.TextField(blank=True, db_column='UpDownPoint', null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='up_down_rate',
            field=models.TextField(blank=True, db_column='UpDownRate', null=True),
        ),
        migrations.AddConstraint(
            model_name='market',
            constraint=models.UniqueConstraint(fields=('stock_name', 'price_time'), name='unique_stockname_pricetime'),
        ),
    ]
