# Generated by Django 5.1 on 2024-09-06 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_alter_market_current_point_alter_market_price_time_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='market',
            name='unique_stockname_pricetime',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='current_point',
            new_name='CurrentPoint',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='stock_name',
            new_name='StockName',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='up_down_flag',
            new_name='UpDownFlag',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='up_down_point',
            new_name='UpDownPoint',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='up_down_rate',
            new_name='UpDownRate',
        ),
    ]
