# Generated by Django 5.1 on 2024-09-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_market_unique_stockname_pricetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='StockName',
            field=models.CharField(db_column='StockName', max_length=255),
        ),
    ]
