# Generated by Django 5.1 on 2024-09-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_alter_market_stockname'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTime',
            fields=[
                ('stock_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=10)),
                ('status_code', models.CharField(blank=True, max_length=20, null=True)),
                ('current_price', models.IntegerField()),
                ('UpDownPoint', models.IntegerField(blank=True, null=True)),
                ('PlusMinus', models.IntegerField(blank=True, null=True)),
                ('UpDownRate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('opening_price', models.IntegerField(blank=True, null=True)),
                ('high_price', models.IntegerField(blank=True, null=True)),
                ('low_price', models.IntegerField(blank=True, null=True)),
                ('price_time', models.DateTimeField(blank=True, null=True)),
                ('per', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pbr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stockcount', models.IntegerField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'real_time',
            },
        ),
        migrations.RemoveConstraint(
            model_name='market',
            name='unique_stockname_pricetime',
        ),
        migrations.AlterUniqueTogether(
            name='market',
            unique_together={('StockName', 'price_time')},
        ),
        migrations.AlterField(
            model_name='market',
            name='StockName',
            field=models.CharField(db_column='StockName', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='realtime',
            unique_together={('stock_code', 'id')},
        ),
        migrations.RemoveField(
            model_name='market',
            name='id',
        ),
    ]
