# Generated by Django 5.1 on 2024-09-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_realtime_remove_market_unique_stockname_pricetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilteredOnceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('closing_price', models.BigIntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'filtered_once_time',
                'unique_together': {('stock_code', 'date')},
            },
        ),
    ]
